on: pull_request

jobs:
  test:
    name: Checks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Install deps
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Run tests
      run: npm run test:ci
    
    - name: Run build
      run: npm run build
