name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'BlobDevelopment' }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Install deps
      run: npm ci

    - name: Check size
      run: npm run record-sizes

    - name: Version
      run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} npx changeset version

    # Make sure package-lock.json is updated
    - name: Re-install
      run: npm install

    - name: Build
      run: npm run build

    - name: Create Release PR or publish
      uses: changesets/action@v1
      with:
        publish: npx changeset publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
